[package]
name = "cs201"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.36.2", features = ["serialize"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
rand = "0.9.0-alpha.2"
serde_path_to_error = "0.1.16"
